blog/urls.py
from django.urls import path

from .feeds import PostsFeed
from .views import post_detail, post_list, post_share_by_email

app_name = "blog"


urlpatterns = [
    path("", post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/", post_detail, name="post_detail"
    ),
    path("<int:post_id>/share/", post_share_by_email, name="post_share_by_email"),
    path("feeds/", PostsFeed(), name="posts_feeds"),
    path("feeds/<int:count>/", PostsFeed(), name="latest_posts_feeds"),
]

portfolio/urls.py
from django.conf import settings
from django.urls import path

from .views import contact, feed, home, search

app_name = "portfolio"


urlpatterns = [
    path("", home, name="home"),
    path("feeds/", feed, name="feeds"),
    path("contact/", contact, name="contact"),
]

# Use PostgreSQL full-text search engine in production
if not settings.DEBUG:
    urlpatterns += [path("search/", search, name="search")]

portfolio_project/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from blog.sitemaps import PostSiteMap

sitemaps = {
    "blog-posts": PostSiteMap,
}

PROJECT_ADMIN_URL = os.environ.get("PROJECT_ADMIN_URL", "admin/")

urlpatterns = [
    path(PROJECT_ADMIN_URL, admin.site.urls),
    path("", include("portfolio.urls", namespace="portfolio")),
    path("blog/", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

# Using the django-haystack search only for development for now.
if settings.DEBUG:
    urlpatterns += [path("search/", include("haystack.urls"))]

portfolio/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

portfolio/forms.py
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV3
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    question = forms.CharField(widget=forms.Textarea)
    captcha = ReCaptchaField(widget=ReCaptchaV3)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["captcha"].label = False

portfolio/views.py
import os

from django.contrib.postgres import search as psql_search
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render

from blog.models import Post

from .forms import ContactForm


def home(request):
    return render(request, "portfolio/home.html", {"active": "home"})


def feed(request):
    return render(request, "portfolio/feeds.html", {"active": "feeds"})


def search(request):
    query = request.GET.get("q")
    page_number = request.GET.get("page")

    search_vector = (
        psql_search.SearchVector("title", weight="A")
        + psql_search.SearchVector("body", weight="A")
        + psql_search.SearchVector("summary", weight="B")
    )
    search_query = psql_search.SearchQuery(query)
    posts = (
        Post.published.annotate(
            rank=psql_search.SearchRank(search_vector, search_query)
        )
        .filter(rank__gte=0.3)
        .order_by("-rank")
    )

    paginator = Paginator(posts, os.environ.get("SEARCH_RESULTS_PER_PAGE", 6))

    try:
        posts = paginator.page(number=page_number)
    except PageNotAnInteger:
        posts = paginator.page(number=1)  # first page
    except EmptyPage:
        posts = paginator.page(number=paginator.num_pages)  # last page

    return render(
        request,
        "portfolio/search.html",
        {"posts": posts, "active": "home", "query": query},
    )


def contact(request):
    sent = False

    if request.method == "POST":
        form = ContactForm(data=request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            question = form.cleaned_data["question"]

            # send email
            subject = f"{name}({email}) has a question for you."
            message = question
            sender = os.environ.get("EMAIL_SENDER_EMAIL")
            send_mail(
                subject, message, from_email=sender, recipient_list=[sender],
            )
            sent = True
    else:
        form = ContactForm()

    return render(
        request,
        "portfolio/contact.html",
        {"active": "contact", "sent": sent, "form": form},
    )

portfolio/templates/portfolio/contact.html
<!-- portfolio/contact.html -->

{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ block.super }} - Contact RealNitinWorks
{% endblock title %}

<!-- Dynamic content on banner overlay -->
{% block banner_content %}
<div class="col d-flex align-items-center justify-content-center">
    <div class="text-center">
        <h1 class="display-5">Contact Me</h1>
        <hr class="hr-accent">
    </div>
</div>
{% endblock banner_content %}
<!-- Dynamic content on banner overlay ends -->

<!-- Page content sections -->
{% block content %}

<!-- Section 1-->
<div class="email-share-form p-5 d-flex justify-content-center normal-text section-primary section-boundary">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% if sent %}
                <h3>
                    <a href="{% url 'portfolio:home' %}">RealNitinWorks</a> will look into your query.
                </h3>
                {% else %}
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-warning btn-block" type="submit" value="Send">
                </form>
                {% endif %}                
            </div>
        </div>
    </div>
</div>
<!-- Section 1 ends -->

{% endblock content %}

portfolio/templates/portfolio/feeds.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ block.super }} - Feeds
{% endblock title %}

<!-- Dynamic content on banner overlay -->
{% block banner_content %}
<div class="col-sm-12 d-flex align-items-center justify-content-center">
    <div class="text-center">
        <h1 class="display-4">Feeds</h1>
        <h4>Subscribe to feeds here</h4>
        <hr class="hr-accent">
    </div>
</div>
{% endblock banner_content %}
<!-- Dynamic content on banner overlay ends -->

<!-- Page content sections -->
{% block content %}

<!-- Section 1 -->
<section id="feeds" class="section-boundary normal-text p-5">
    <div class="container">
        <h3 class="mb-4">The following feeds are available.</h3>
        <ul class="list-group">
            <li class="list-group-item bg-dark">
                <span class="badge badge-info p-2">All Blog Posts</span> -
                <a href="{% url 'blog:posts_feeds' %}">{% url 'blog:posts_feeds' %}</a>
            </li>
            <li class="list-group-item bg-dark">
                <span class="badge badge-info p-2">10 Latest Blog Posts</span> -
                <a href="{% url 'blog:latest_posts_feeds' 10 %}">{% url 'blog:latest_posts_feeds' 10 %}</a>
            </li>
        </ul>
    </div>
</section>
<!-- Section 1 ends -->

{% endblock content %}
<!-- Page content ends -->

portfolio/templates/portfolio/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ block.super }} - Home
{% endblock title %}

<!-- Dynamic content on banner overlay -->
{% block banner_content %}
<div class="col-sm-6 d-flex align-items-center justify-content-center">
    <div class="text-center">
        <h1 class="display-4">Nitin Cherian</h1>
        <h2>Programmer, Learner and Blogger</h2>
        <hr class="hr-accent">
    </div>
</div>
<div class="col-sm-6 d-flex justify-content-center align-items-center">
    <picture>
        <img src="{% static "assets/img/me.png" %}" class="img-fluid rounded-circle shadow-lg" alt="Picture of Me">
    </picture>
</div>
{% endblock banner_content %}
<!-- Dynamic content on banner overlay ends -->

<!-- Page content sections -->
{% block content %}

<!-- Section 1 -->
<section id="about" class="section-boundary">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 d-none d-lg-block"><img class="img-fluid shadow-lg"
                    src="{% static "assets/img/skills_list.jpeg" %}" style="height: 600px;"></div>
            <div class="col-lg-6">
                <h3 class="pb-2"><span class="heading-underline">About Me</span></h3>
                <p class="text-left normal-text">I am Nitin George Cherian. Software Engineer and Blogger. I live in
                    Bangalore&nbsp;with my wife and two lovely boys.</p>
                <p class="text-left normal-text">I love programming and the web. Python is my favourite language.
                    Interested&nbsp;in distributed systems and concurrent systems.</p>
                <p class="text-left normal-text">During my free time, I do side projects, blog and polishes my
                    skills in
                    programming and&nbsp;design.</p>
                <div class="row normal-text" style="padding-top: 41px;">
                    <div class="col-lg-6">
                        <ul>
                            <li>Python</li>
                            <li>C/C++</li>
                            <li>Django</li>
                            <li>Flask</li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <ul>
                            <li>Docker</li>
                            <li>Git</li>
                            <li>Pytest</li>
                            <li>Javascript</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Section 1 ends -->

{% endblock content %}
<!-- Page content ends -->

portfolio/templates/portfolio/search.html
<!-- portfolio/search.html -->

{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}

{% block title %}
{{ block.super }} - Search Results
{% endblock title %}

<!-- Dynamic content on banner overlay -->
{% block banner_content %}
<div class="col-sm-12 d-flex align-items-center justify-content-center">
    <div class="text-center">
        {% if query %}
        <!-- Banner text for search results header -->
        <h1>
            Search Results for <span class="badge badge-success">"{{ query }}"</span>
        </h1>
        {% with posts.paginator.count as total_results %}
        <h4>Found <span class="badge badge-primary">{{ total_results }}</span> result{{ total_results|pluralize }}</h4>
        {% endwith %}
        <hr class="hr-accent">
        {% else %}
        <h1>You did not enter a query</h1>
        {% endif %}
    </div>
</div>
{% endblock banner_content %}
<!-- Dynamic content on banner overlay ends -->

<!-- Page content sections -->
{% block content %}

{% with posts.paginator.count as total_results %}
{% if total_results %}
<!-- Section 1-->
<div id="search-results" class="similar-posts text-left normal-text section-boundary">
    <div class="container p-5">
        <h3 class="text-white">Results</h3>
        <hr class="hr-accent">
        <ul class="text-white">
            {% for post in posts %}
            <li>
                <p>
                    <a class="text-success" href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </p>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

<!-- Pagination links -->
<div class="section-primary section-boundary">
    <div class="container p-5">
        {% include 'pagination.html' with page=posts query=query next=">>" previous="<<"%}
    </div>
</div>
<!-- Pagination ends -->
<!-- Section 1 ends -->
{% endif %}
{% endwith %}

{% endblock content %}