blog/urls.py
from django.urls import path

from .feeds import PostsFeed
from .views import post_detail, post_list, post_share_by_email

app_name = "blog"


urlpatterns = [
    path("", post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/", post_detail, name="post_detail"
    ),
    path("<int:post_id>/share/", post_share_by_email, name="post_share_by_email"),
    path("feeds/", PostsFeed(), name="posts_feeds"),
    path("feeds/<int:count>/", PostsFeed(), name="latest_posts_feeds"),
]

portfolio_project/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from blog.sitemaps import PostSiteMap

sitemaps = {
    "blog-posts": PostSiteMap,
}

PROJECT_ADMIN_URL = os.environ.get("PROJECT_ADMIN_URL", "admin/")

urlpatterns = [
    path(PROJECT_ADMIN_URL, admin.site.urls),
    path("", include("portfolio.urls", namespace="portfolio")),
    path("blog/", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

# Using the django-haystack search only for development for now.
if settings.DEBUG:
    urlpatterns += [path("search/", include("haystack.urls"))]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="published")


class Post(models.Model):
    STATUS_CHOICES = (("draft", "Draft"), ("published", "Published"))

    title = models.CharField(max_length=250)
    summary = models.CharField(max_length=500)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")
    objects = models.Manager()  # The default model manager
    published = PublishedManager()  # The custom manager
    tags = TaggableManager()  # Tag support

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=250)
    email = models.EmailField()
    body = models.TextField()
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"{self.body} by {self.name} on {self.post}"

blog/forms.py
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV3
from django import forms
from pagedown.widgets import AdminPagedownWidget

from .models import Comment, Post


class PostAdminForm(forms.ModelForm):
    """
    This class is used to render Stack Overflow's "Pagedown" Markdown editor
    to Django Admin for the Post model.

    https://github.com/timmyomahony/django-pagedown
    """

    body = forms.CharField(widget=AdminPagedownWidget())

    class Meta:
        model = Post
        fields = "__all__"


class PostEmailForm(forms.Form):
    """
    Form for sharing post by email.
    """

    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False, widget=forms.Textarea)
    captcha = ReCaptchaField(widget=ReCaptchaV3)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["captcha"].label = False


class PostCommentForm(forms.ModelForm):
    captcha = ReCaptchaField(widget=ReCaptchaV3)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["captcha"].label = False

    class Meta:
        model = Comment
        fields = ("name", "email", "body")

blog/views.py
import os

from django.contrib import messages
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from taggit.models import Tag

from .forms import PostCommentForm, PostEmailForm
from .models import Post


def post_list(request, tag_slug=None):
    all_posts = Post.published.all()

    tag = None
    if tag_slug:
        # Filter posts based on tag_slug input
        tag = get_object_or_404(Tag, slug=tag_slug)
        all_posts = all_posts.filter(tags__in=[tag])

    paginator = Paginator(all_posts, os.environ.get("POSTS_PER_PAGE", 3))
    page_number = request.GET.get("page")  # query string in url

    try:
        posts = paginator.page(number=page_number)
    except PageNotAnInteger:
        posts = paginator.page(number=1)  # first page
    except EmptyPage:
        posts = paginator.page(number=paginator.num_pages)  # last page

    return render(
        request,
        "blog/post/post_list.html",
        {"all_posts": all_posts, "posts": posts, "active": "blog", "tag": tag},
    )


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(
        Post, publish__year=year, publish__month=month, publish__day=day, slug=slug
    )

    if request.method == "POST":
        form = PostCommentForm(request.POST)
        if form.is_valid():
            # Create 'Comment' model instance backing the form
            # but don't write to DB until for comment-post association
            new_comment = form.save(commit=False)
            # Associate post to the comment
            new_comment.post = post
            # Save to DB
            new_comment.save()
            # Message on successful submit
            messages.add_message(request, messages.SUCCESS, "Your comment is submitted")
            # Redirect to this view
            return redirect(to=post)
    else:
        form = PostCommentForm()

    # Get all the active comments of this post
    all_comments = post.comments.filter(active=True)
    comments_paginator = Paginator(all_comments, os.environ.get("COMMENTS_PER_PAGE", 6))
    comments_page_number = request.GET.get("page")  # query string in url

    try:
        comments = comments_paginator.page(number=comments_page_number)
    except PageNotAnInteger:
        comments = comments_paginator.page(number=1)
    except EmptyPage:
        comments = comments_paginator.page(number=comments_paginator.num_pages)

    # Get similar posts by tags
    tags = post.tags.all()
    # post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = (
        Post.published.filter(tags__in=tags)
        .exclude(id=post.id)
        .annotate(same_tags=Count("tags"))
        .order_by("-same_tags", "-publish")[:3]
    )

    return render(
        request,
        "blog/post/post_detail.html",
        {
            "post": post,
            "active": "blog",
            "comments": comments,
            "form": form,
            "similar_posts": similar_posts,
        },
    )


def post_share_by_email(request, post_id):
    post = get_object_or_404(Post, id=post_id, status="published")
    sent = False

    if request.method == "POST":
        form = PostEmailForm(request.POST)
        if form.is_valid():  # Validate and get the cleaned data
            cleaned_data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cleaned_data['name']} recommends you read " f"{post.title}"
            message = (
                f"Read {post.title} at {post_url}\n\n"
                f"{cleaned_data['name']}'s comments: {cleaned_data['comment']}"
            )
            sender = os.environ.get("EMAIL_SENDER_EMAIL")
            send_mail(subject, message, sender, [cleaned_data["to"]])
            sent = True
    else:
        form = PostEmailForm()

    return render(
        request,
        "blog/post/post_share_email.html",
        {"form": form, "sent": sent, "post": post, "active": "blog"},
    )

blog/templates/blog/post/latest_posts.html
<!-- blog/post/latest_posts.html -->

<ul>
    {% for post in latest_posts %}
    <li>
        <p>
            <a class="text-warning" href="{{ post.get_absolute_url }}">{{ post }}</a>
        </p>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post/post_detail.html
<!-- blog/post/post_detail.html -->

{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }} - Blog - {{ post.title }}
{% endblock title %}

<!-- Dynamic content on banner overlay -->
{% block banner_content %}
<div class="col d-flex align-items-center justify-content-center">
    <div class="text-center">
        <h1 class="display-4">{{ post.title }}</h1>
        <h2>{{ post.summary }}</h2>
        <p>Author: {{ post.author|title }} | Published: {{ post.publish|date:"D, d M, Y" }}</p>
        {% post_tags post %}
        <!-- Inclusion tag for tags display -->
        <hr class="hr-accent">
    </div>
</div>
{% endblock banner_content %}
<!-- Dynamic content on banner overlay ends -->

<!-- Page content sections -->
{% block content %}

<!-- Section 1-->
<div class="d-flex justify-content-center section-primary p-5 post-detail">
    <div class="container">
        <span class="post-text">{{ post.body|markdown }}</span>
        <div class="mt-5">
            <span class="text-muted h4">Share this post: </span>
            <a href="{% url 'blog:post_share_by_email' post.id %}"><i class="fa fa-envelope fa-2x"
                    title="E-mail"></i></a>
        </div>
    </div>
</div>
<!-- Section 1 ends -->

<!-- comments section -->

<div id="comments_section" class="p-5 section-boundary">
    <div class="container">

        <!-- Total comments part -->
        <!-- Important! - comments is a Django Page object -->
        {% with comments.paginator.count as total_comments %}
        {% if total_comments %}
        <p class="text-right">{{ total_comments }} comment{{ total_comments|pluralize }}</p>
        {% endif %}
        {% endwith %}
        <hr>

        <!-- Comments -->
        {% for comment in comments %}
        <div class="{% cycle 'odd-comment' 'even-comment' %} p-2">
            <!-- https://docs.djangoproject.com/en/3.0/topics/pagination/ -->
            <!-- https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#for -->
            <!-- Adding in for loop: https://stackoverflow.com/a/24912805/1220250-->
            <span class="badge badge-success">#{{ forloop.counter0|add:comments.start_index }} </span>
            <span class="badge badge-warning">{{ comment.name|title }}</span> said
            <span class="badge badge-info">{{ comment.created|naturaltime }}</span>
            <p>
                {{ comment.body|markdown }}
            </p>
        </div>
        {% endfor %}
        <!-- Comments end -->

        <!-- Pagination for the comments -->
        {% if comments %}
        <hr>
        {% include 'comments_pagination.html' with page=comments %}
        {% endif %}
        <!-- Pagination for the comments ends -->

        <!-- Form for submitting comments -->
        <h3 class="mt-4">Leave a comment</h3>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-warning" value="Submit">
        </form>
        <!-- Comment form ends -->
    </div>
</div>

<!-- comments section ends -->

<!-- Section 2: Similar posts -->
<div class="similar-posts text-left normal-text section-boundary">
    <div class="container p-5">
        <h3 class="text-white">Similar Posts</h3>
        <hr class="hr-accent">
        <ul class="text-white">
            {% for post in similar_posts %}
            <li>
                <p>
                    <a class="text-success" href="{{ post.get_absolute_url }}">
                        {{ post }}
                    </a>
                </p>
            </li>
            {% empty %}
            <li>No posts similar to this post yet.</li>
            {% endfor %}
        </ul>
    </div>
</div>
<!-- Section 2 ends-->

{% endblock content %}

blog/templates/blog/post/post_list.html
<!-- blog/post/post_list.html -->

{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}

{% block title %}
{{ block.super }} - Blog Posts
{% endblock title %}

<!-- Dynamic content on banner overlay -->
{% block banner_content %}
<div class="col-sm-12 d-flex align-items-center justify-content-center">
    <div class="text-center">
        <!-- Important! posts is a Page object and paginated -->
        {% if tag %}
        <!-- Banner text for posts filtered by tag -->
        <h1 class="display-4">Posts tagged with
            <span class="badge badge-success">
                <a class="tag-link" href="{% url "blog:post_list_by_tag" tag.slug %}">
                    "{{ tag.name }}"
                </a>
            </span>
        </h1>
        {% with posts.paginator.count as posts_count %}
        <!-- All the posts passed into this template have this tag irrespective of pagination -->
        <h4>Found <span class="badge badge-primary">{{ posts_count }}</span> post{{ posts_count|pluralize }}</h4>
        {% endwith %}

        {% else %}
        <!-- Banner text for all posts (no filtering on tags) -->
        <h1 class="display-4">My Blog</h1>
        <h4>The Blog has <span class="badge badge-primary">{% total_posts %}</span> posts</h4>
        {% endif %}

        <hr class="hr-accent">
    </div>
</div>
{% endblock banner_content %}
<!-- Dynamic content on banner overlay ends -->

<!-- Page content sections -->
{% block content %}

<!-- Section 1-->
<div class="section-primary">
    <div class="container-fluid">
        <div class="row">
            <!-- Post list -->
            <div class="col-12 col-lg-9 h-100">
                <div class="row">
                    {% for post in posts %}
                    <div
                        class="post-list-grid col-12 normal-text {% cycle 'section-primary' 'section-secondary' %} shadow-lg p-2 pt-5 pr-5 pl-5">
                        <!-- Post metadata -->
                        <a href="{{ post.get_absolute_url }}">
                            <h2>{{ post.title }}</h2>
                            <p class="text-info">{{ post.summary }}</p>
                            <div class="text-success">
                                Author: <span class="badge badge-warning">
                                    {{ post.author|title }}
                                </span> | <span class="badge badge-info">{{ post.publish|date:"M d, Y" }}
                                </span>
                            </div>
                        </a>
                        <!-- Post metadata ends -->

                        <!-- Post tags list -->
                        {% post_tags post %}
                        <!-- Inclusion tag for tags display -->
                        <!-- Post tags list ends -->
                    </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Post list ends -->

            <!-- Blog stats Sidebar -->
            <div class="col-12 col-lg-3 normal-text text-white post-list-sidebar">
                <h1 class="display-5 text-center pt-3 pr-3 pl-3 pb-1">Blog Stats</h1>
                <hr class="hr-accent">
                <div class="p-3">
                    <h3 class="mt-4">Latest Posts</h3>
                    {% show_latest_posts 3 %}
                </div>
                <div class="mt-3 p-3">
                    <h3 class="mt-4">Most Commented Posts</h3>
                    {% get_most_commented_posts 3 as most_commented_posts %}
                    <ul>
                        {% for post in most_commented_posts %}
                        <li>
                            <p>
                                <a class="text-info" href="{{ post.get_absolute_url }}">{{ post }}</a>
                                <span class="badge badge-success">{% total_active_comments post %}</span>
                            </p>
                        </li>
                        {% endfor %}
                    </ul>
                    {% if not most_commented_posts %}
                    <div class="progress mt-3">
                        <div class="progress-bar progress-bar-striped progress-bar-animated bg-info" role="progressbar"
                            aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%"></div>
                    </div>
                    <p class="text-info mt-2 pl-2">Posts are picking up momentum ...</p>
                    {% endif %}
                </div>
                <div class="mt-3 p-3">
                    <h3>Popular tags</h3>
                    {% popular_tags 2 as pop_tags %}
                    {% for tag in pop_tags %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                        <span class="badge badge-primary">
                            <!-- https://github.com/jazzband/django-taggit/blob/master/taggit/managers.py -->
                            <!-- https://github.com/jazzband/django-taggit/issues/203#issue-28636008 -->
                            {{ tag.name }}({{ tag.num_times }})
                        </span>
                    </a>
                    {% empty %}
                    <div class="progress mt-3">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                            aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%"></div>
                    </div>
                    <p class="text-primary mt-2 pl-2">Tags are picking up momentum ...</p>
                    {% endfor %}
                </div>
            </div>
            <!-- Blog stats sidebar ends -->
        </div>
    </div>
</div>

<!-- Pagination links -->
<div class="section-primary section-boundary">
    <div class="container p-5">
        {% include 'pagination.html' with page=posts next="Older Posts" previous="Newer Posts"%}
    </div>
</div>
<!-- Pagination ends -->
<!-- Section 1 ends -->

{% endblock content %}

blog/templates/blog/post/post_share_email.html
<!-- blog/post/post_share_email.html -->

{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }} - Email - {{ post.title }}
{% endblock title %}

<!-- Dynamic content on banner overlay -->
{% block banner_content %}
<div class="col d-flex align-items-center justify-content-center">
    <div class="text-center">
        <h1 class="display-5">Email '{{ post.title }}'</h1>
        <hr class="hr-accent">
    </div>
</div>
{% endblock banner_content %}
<!-- Dynamic content on banner overlay ends -->

<!-- Page content sections -->
{% block content %}

<!-- Section 1-->
<div class="email-share-form p-5 d-flex justify-content-center normal-text section-primary section-boundary">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% if sent %}
                <h3>
                    Email Sent!
                </h3>
                {% else %}
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-warning btn-block" type="submit" value="Send">
                </form>
                {% endif %}
                <a class="mt-3 d-inline-block" href="{{ post.get_absolute_url }}">Back to Post</a>
            </div>
        </div>
    </div>
</div>
<!-- Section 1 ends -->

{% endblock content %}

blog/templates/blog/post/post_tags.html
<!-- blog/post/post_tags.html -->
<div class="mt-2 mb-2">
    <i class="fa fa-tags"></i>
    {% for tag in tags %}
    <a class="tag-link" href="{% url "blog:post_list_by_tag" tag.slug %}">
        <span class="badge badge-primary">{{ tag.name }}</span>
    </a>
    {% endfor %}
</div>