blog/urls.py
from django.urls import path

from .feeds import PostsFeed
from .views import post_detail, post_list, post_share_by_email

app_name = "blog"


urlpatterns = [
    path("", post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:slug>/", post_detail, name="post_detail"
    ),
    path("<int:post_id>/share/", post_share_by_email, name="post_share_by_email"),
    path("feeds/", PostsFeed(), name="posts_feeds"),
    path("feeds/<int:count>/", PostsFeed(), name="latest_posts_feeds"),
]

portfolio/urls.py
from django.conf import settings
from django.urls import path

from .views import contact, feed, home, search

app_name = "portfolio"


urlpatterns = [
    path("", home, name="home"),
    path("feeds/", feed, name="feeds"),
    path("contact/", contact, name="contact"),
]

# Use PostgreSQL full-text search engine in production
if not settings.DEBUG:
    urlpatterns += [path("search/", search, name="search")]

portfolio_project/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from blog.sitemaps import PostSiteMap

sitemaps = {
    "blog-posts": PostSiteMap,
}

PROJECT_ADMIN_URL = os.environ.get("PROJECT_ADMIN_URL", "admin/")

urlpatterns = [
    path(PROJECT_ADMIN_URL, admin.site.urls),
    path("", include("portfolio.urls", namespace="portfolio")),
    path("blog/", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

# Using the django-haystack search only for development for now.
if settings.DEBUG:
    urlpatterns += [path("search/", include("haystack.urls"))]

templates/base.html
{% load static %}
{% load portfolio_tags %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}RealNitinWorks{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'assets/img/favicon-me.ico' %}" />
    <link rel="stylesheet" href="{% static "assets/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono">
    <link rel="stylesheet" href="{% static "assets/fonts/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/styles.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/monokai.css" %}">
</head>

<body style="font-family: 'Roboto Mono', monospace; overflow-x: hidden;">
    <!-- Navbar -->
    {% include 'navbar.html'%}

    <!-- Messages -->
    {% include 'message.html' %}

    <!-- Banner with overlay below the Navbar -->
    <div id="banner" class="header pt-5 p-md-none section-boundary">
        <div class="row h-100">
            <div class="col-md-12 d-flex h-100 flex-column flex-sm-row">
                <!-- Dyanamic content on top of the banner -->
                {% block banner_content %}
                {% endblock banner_content %}
                <!-- Dyanamic content ends -->
            </div>
        </div>
    </div>
    <!-- Banner ends -->

    <!-- Sections -->
    {% block content %}
    {% endblock content %}

    <!-- Quote section: Display random quote -->
    {% quote %}
    <!-- Quote section ends -->

    <!-- Footer -->
    {% include 'footer.html' %}

    <!-- Javascript libs -->
    <script src="{% static "assets/js/jquery.min.js" %}"></script>
    <script src="{% static "assets/bootstrap/js/bootstrap.min.js" %}"></script>

    <!-- jquery for bootstrap toasts -->
    <script>
        $(document).ready(function() {
            $('.toast').toast('show');
        });
    </script>
</body>

</html>

templates/comments_pagination.html
<!-- comments_pagination.html -->

<div class="d-flex justify-content-between comments-pagination">
    <div class="pl-2 pr-2 pb-1">
        {% if page.has_previous %}
        <a class="text-white" href="?page={{ page.previous_page_number }}#comments_section">
            <i class="fa fa-angle-double-left" aria-hidden="true"></i>
        </a>
        {% else %}
        <a class="text-muted disabled" aria-disabled="true" href="#comments_section">
            <i class="fa fa-angle-double-left" aria-hidden="true"></i>
        </a>
        {% endif %}
    </div>
    <div class="pl-2 pr-2 pb-1">
        {% if page.has_next %}
        <a class="text-white" href="?page={{ page.next_page_number }}#comments_section">
            <i class="fa fa-angle-double-right" aria-hidden="true"></i>
        </a>
        {% else %}
        <a class="text-muted disabled" aria-disabled="true" href="#comments_section">
            <i class="fa fa-angle-double-right" aria-hidden="true"></i>
        </a>
        {% endif %}
    </div>
</div>

templates/footer.html
<!-- Footer -->
<footer style="padding: 20px;">
    <div class="container">
        <div class="row text-center" style="padding: 10px;">
            <div class="col">
                <a href="https://github.com/realnitinworks">
                    <i class="fa fa-github" style="font-size: 42px;padding: 10px;"></i>
                </a>
                <a href="https://twitter.com/nitin_cherian">
                    <i class="fa fa-twitter" style="font-size: 42px;padding: 10px;"></i>
                </a>
                <a href="https://www.linkedin.com/in/nitin-george-cherian-54b77828/">
                    <i class="fa fa-linkedin" style="font-size: 42px;padding: 10px;"></i></div>
            </a>
        </div>
        <div class="row text-center">
            <div class="col">
                <p>Copyright&nbsp;<i class="fa fa-copyright"></i>&nbsp;RealNitinWorks 2020</p>
            </div>
        </div>
    </div>
</footer>
<!-- Footer ends -->

templates/message.html
<!-- message.html -->
<!-- Display the messages on successful form submission for example -->
<!-- https://docs.djangoproject.com/en/3.0/ref/contrib/messages/ -->

<!-- Using bootstrap toast for showing the message -->
<!-- https://getbootstrap.com/docs/4.3/components/toasts/ -->
{% if messages %}
{% for message in messages %}
<div class="base-toast">
    <div class="toast" data-autohide="false" style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; margin: auto;">
        <div class="toast-header">
            <strong class="mr-auto text-primary">Comment submitted - RealNitinWorks</strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast">&times;</button>
        </div>
        <div class="toast-body">
            {{ message }}
        </div>
    </div>
</div>
{% endfor %}
{% endif %}

templates/navbar.html
<!-- navbar.html-->
{% load blog_tags %}

<!-- Navbar -->
<nav class="navbar navbar-light navbar-expand-md section-boundary">
    <div class="container-fluid">
        <a class="navbar-brand text-white ml-5" href="{% url "portfolio:home" %}" style="font-size: 24px;">
            <strong>RealNitinWorks</strong>
        </a>
        <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="nav navbar-nav ml-auto mr-5">
                <li class="nav-item" role="presentation">
                    <a class="nav-link text-white {% if active == "home" %} shadow-lg {% endif %}"
                        href="{% url "portfolio:home" %}">
                        Home
                    </a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link text-white  {% if active == "portfolio" %} shadow-lg {% endif %}" href="#">
                        Portfolio
                    </a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link text-white  {% if active == "blog" %} shadow-lg {% endif %}"
                        href="{% url "blog:post_list" %}">
                        Blog <span class="badge badge-primary">{% total_posts %}</span>
                    </a>
                </li>
                <!-- Search form -->
                <form class="form-inline my-2 my-lg-0 ml-md-3" method="get" action="/search/">
                    <input class="form-control mr-sm-2" required type="search" placeholder="Search Posts"
                        aria-label="Search" name="q">
                </form>
                <!-- Search form ends -->
                <li class="nav-item" role="presentation">
                    <a class="nav-link text-white  {% if active == "feeds" %} shadow-lg {% endif %}"
                        href="{% url 'portfolio:feeds' %}">
                        Feeds
                    </a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link text-white  {% if active == "contact" %} shadow-lg{% endif %}"
                        href="{% url 'portfolio:contact' %}">
                        Contact
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>
<!-- Navbar ends -->

templates/pagination.html
<div id="pagination" class="row">
    <div class="col-12">
        <nav aria-label="post pagination nav">
            <ul class="pagination justify-content-center">
                <!-- Newer posts appear first -->
                {% if page.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.previous_page_number }}{% if query %}&q={{query}}{% endif %}">{{ previous }}</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">{{ previous }}</a>
                </li>
                {% endif %}

                <!-- Current page -->
                <li class="page-item disabled">
                    <a class="page-link" href="#">Page {{ page.number }} of {{ page.paginator.num_pages }}</a>
                </li>

                <!-- Older posts appear later -->
                {% if page.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.next_page_number }}{% if query %}&q={{query}}{% endif %}">{{ next }}</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">{{ next }}</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>